const Routes = {
    Splash: 'Splash',
    Main: 'Main',
    SignIn: 'SignIn',
    SignUp: 'SignUp',
    ForgotPassword: 'ForgotPassword',
    VerifyPasswordScreen: 'VerifyPasswordScreen',
    Home: 'Home',
    Downloads: 'Downloads',
    Browse: 'Browse',
    Search: 'Search',
    ListCourses: 'ListCourses',
    CourseDetail: 'CourseDetail',
    Profile: 'Profile',
    Settings: 'Settings',
    SearchAll: 'SearchAll',
    SearchCourses: 'SearchCourses',
    SearchPaths: 'SearchPaths',
    SearchAuthors: 'SearchAuthors',
    SkillsDetail: 'SkillsDetail',
    ListCoursesByTypeScreen: 'ListCoursesByTypeScreen',
    AllPathsScreen: 'AllPathsScreen',
    CourseContent: 'CourseContent',
    CourseTranscript: 'CourseTranscript',
    SendFeedbackScreen: 'SendFeedbackScreen',
    AuthorScreen: 'AuthorScreen',
    NewReleasesScreen: 'NewReleasesScreen',
    PathScreen: 'PathScreen',
    Favourites: 'Favourites',
    CategoryDetailScreen: 'CategoryDetailScreen',
    RecommendedForYouScreen: 'RecommendedForYouScreen',
    MeScreen: 'MeScreen',
    MyCoursesTab: 'MyCoursesTab',
}

export default Routes